### ISSUE TITLE
Update API examples with v4 search/autocomplete

### ISSUE THREAD

**Issue by amanji** [bcgov/orgbook-bc-api-docs#19]
The examples reference the now deprecated v3 version of search and autocomplete. A newer/shinier v4 update is available

**Comment by swcurran** [comment]
Note that there was a link in the OrgBook UI that referenced the `/demo` folder.  The link has been temporarily changed to the main README.md with a "coming soon" message. When this is ready, we need to update the link back to the demo.

**Comment by amanji** [comment]
Is this related to #25 ? Or is that link broken in the docs here in this repo?

**Comment by swcurran** [comment]
Link is broken in orgbook-bc-client, and I've got a PR in to fix that.  

I've moved #25 to the orgbook-bc-client repo where it belongs. Sorry about that.
