### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by amanji** [bcgov/orgbook-bc-api-docs#22]
This repo should be renamed to properly express what it is. I suggest renaming to `orgbook-bc-api-documentation` as this is not technically an API and has specific guidance for OrgBook BC API rather than a more generic OrgBook (Aries VCR) implementation.

**Comment by amanji** [comment]
Thoughts @swcurran?

**Comment by swcurran** [comment]
Agreed -- good idea.  Documentation or Tutorial?  Either way -- whatever you think devs would understand best.

**Comment by WadeBarnes** [comment]
When the name is changed the following repos contain references to `https://github.com/bcgov/orgbook-api`:
- https://github.com/bcgov/orgbook-bc-client
- https://github.com/bcgov/aries-vcr

**Comment by WadeBarnes** [comment]
Let me know what's decided on the name and I can do the name change and make the updates.

**Comment by swcurran** [comment]
@amanji -- over to you to make a decision.  Go for it.

**Comment by amanji** [comment]
I think we can call it: `orgbook-bc-api-docs`. Seems a more apt term for the repo

**Comment by WadeBarnes** [comment]
Renamed.  Two PRs to be merged containing the updated URL:
- https://github.com/bcgov/aries-vcr/pull/726
- https://github.com/bcgov/orgbook-bc-client/pull/119

**Comment by WadeBarnes** [comment]
@amanji, please review close when ready.
