### ISSUE TITLE
Bad Request response when try to paginate after page 10

### ISSUE THREAD

**Issue by Laerte** [bcgov/orgbook-bc-api-docs#35]
I'm filtering by category and paginating to fetch the results, but when I try to paginate after page 10 I get `Bad Request` response from API, this error occurs for all categories.

Working request:
https://www.orgbook.gov.bc.ca/api/v2/search/credential/facets?category%253Aentity_type=XS&ordering=effective_date&page=10&category%3Aentity_type=XS

Failure request (Any number after 10 result in error):
https://www.orgbook.gov.bc.ca/api/v2/search/credential/facets?category%253Aentity_type=XS&ordering=effective_date&page=11&category%3Aentity_type=XS

**Comment by WadeBarnes** [comment]
This is a known issue.  We're limiting paging on purpose to stop people and bots from simply paging through all the records using scripts.  In a typical scenario involving a legitimate user interacting with the UI, or service integration interacting with the API, the query will be more narrow in scope and not require paging beyond 10 pages.

**Comment by Laerte** [comment]
Thanks @WadeBarnes
